name: CI
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Base Ref branch name
        run: |
          echo "${{ github.event.pull_request.head.sha }}";
          echo "${{ github.event.pull_request.base.sha }}"
