on:
  push:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  print_title_of_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Print Title of PR
        shell: bash
        run: |
          if [[ ${{ github.event.pull_request.title }} =~ SGM-[0-9]{1,4}[[:space:]].+ ]] ;
            then exit 0;
          else exit 1;
          fi
