name: CI
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Base Ref SHA
        id: base_sha_short
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
        run: echo "base_sha=${BASE_SHA:0:7}" >> "$GITHUB_OUTPUT"
      - name: Get Head Ref SHA
        id: head_sha_short
        env:
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: echo "head_sha=${HEAD_SHA:0:7}" >> "$GITHUB_OUTPUT"
      - name: Show API results of commit diffs
        shell: python
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          import os
          print(os.environ)
          print(f"https://api.github.com/repos/loic.diridollou/test-action/compare/{os.environ['base_sha']}...{os.environ['head_sha']}")
