name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Base Ref branch name
        run: |
          echo "${{ github.event.pull_request.head.sha }}"
        # Outputs: "main" for main <- PR branch.
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
