name: Check docs were added

on:
  push:
    branches:
      - "*"
      - "!main"

jobs:
  check_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check SHA for base and head
        run: |
          echo ${{ github.event.pull_request.base.sha }};
          echo ${{ github.event.pull_request.head.sha }};
