name: Create Release with new tag

on:
  push:
    tags:
      - "v*"

jobs:
  get_tag_value:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
      - name: Create release
        id: split
        shell: bash
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer  ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/loicdiridollou/test-action/releases \
            -d '{"tag_name": "${{ github.ref }}",
                 "target_commitish":"main",
                 "name": "${{ steps.vars.outputs.tag }}",
                 "body":"Description of the release",
                 "draft": false,
                 "prerelease": false,
                 "generate_release_notes": false}'
