name: Create Release with new tag

on:
  push:
    tags:
      - "v*"

jobs:
  get_tag_value:
    runs-on: ubuntu-latest
    steps:
      - name: Print Title of PR
        shell: bash
        run: |
          tag = ${{ github.ref }};
          echo ${tag##*/};

      - name: Create release
        shell: bash
        if: ${{ !always() }}
        run: |
          tag = "${github.ref##/:}"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer  ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/loicdiridollou/test-action/releases \
            -d '{"tag_name": "${{ github.ref##/: }}",
                 "target_commitish":"main",
                 "name": "${{ github.ref }}",
                 "body":"Description of the release",
                 "draft": false,
                 "prerelease": false,
                 "generate_release_notes": false}'
