name: Create Release with new tag

on:
  push:
    tags:
      - "v*"

jobs:
  get_tag_value:
    runs-on: ubuntu-latest
    steps:
      - name: Split branch name
        env:
          BRANCH: ${{ github.ref }}
        id: split
        run: echo "on tag ${BRANCH##*/}"
