name: Read docs for newly created tag

on: pull_request

jobs:
  print_title_of_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Extract docs for given tag
        shell: python
        id: get_docs
        env:
          tag: v1.2.1
        run: |
          import os
          import re
          from pathlib import Path

          rgx = re.compile(r'## Version \d+\.\d+\.\d+')
          v_major_minor = '.'.join(os.environ['tag'].split('.')[:2])
          body = Path(f'doc/whatsnew/v{v_major_minor}.md').read_text()
          cur_v = rgx.search(body)
          prev_v = rgx.search(body, cur_v.end())

          print(body[cur_v:prev_v.start()])
